sudo: false

language: php

matrix:
  include:
    - php: 7.1
  fast_finish: true

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --prefer-dist --no-interaction

script:
  - ./vendor/bin/php-cs-fixer --verbose --config-file=./.php_cs fix

notifications:
  script:
    - "phpunit --process-isolation"